config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :home_page_sections do
      collection do
        post :update_positions
      end
    end
    resources :home_page_fields
    resources :home_page_section_types
    resources :home_page_field_types
    resource :instagram_settings, only: %i[destroy update]
    resources :instagram_users
    resources :instagram_posts, only: [:index] do
      collection do
        get :download
        get :hashtag
        post :update_all
        get :destroy_all
      end
    end
    namespace :instagram_callbacks do
      get :connect
      get :callback
    end
  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :instagram_posts, only: %i[index]
        resources :home_page_sections, only: %i[index]
      end
    end
  end
end

app/models/spree/instagram_user.rb
module Spree
  class InstagramUser < Spree::Base
    has_many :instagram_posts
    has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::InstagramUserImage'
  end
end

app/controllers/spree/admin/instagram_users_controller.rb
module Spree
  module Admin
    class InstagramUsersController < ResourceController
      def create
        @instagram_user = Spree::InstagramUser.new(instagram_user_basic_params)
        @instagram_user.build_image(attachment: image_params) if image_params
        @instagram_user.instagram_posts << Spree::InstagramPost.find(post_id_param) if post_id_param.present?

        if @instagram_user.save
          flash[:success] = flash_message_for(@instagram_user, :successfully_created)
          if post_id_param.empty?
            redirect_to edit_admin_instagram_user_path(@instagram_user)
          else
            redirect_to hashtag_admin_instagram_posts_path
          end
        else
          flash[:error] = Spree.t(:could_not_create_instagram_user)
          render :new
        end
      end

      def update
        @instagram_user = Spree::InstagramUser.find(params[:id])
        @instagram_user.create_image(attachment: image_params) if image_params
        if @instagram_user.update(instagram_user_basic_params)
          flash[:success] = flash_message_for(@instagram_user, :successfully_updated)
        else
          flash[:error] = Spree.t(:could_not_update_instagram_user)
        end
        render :edit
      end

      private

      def instagram_user_basic_params
        instagram_user_params.slice(:name, :username)
      end

      def image_params
        params[:instagram_user][:image]
      end

      def post_id_param
        params[:instagram_user][:post_id]
      end

      def instagram_user_params
        params.require(:instagram_user).permit(:name, :username, :image)
      end
    end
  end
end

app/views/spree/admin/instagram_users/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @home_page_field } %>

<div class="row">
  <div class="col-sm-12">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :username, class: ['form-group'] do %>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
      <%= f.error_message_on :username %>
    <% end %>

    <%= f.field_container :image, class: ['form-group'] do %>
      <%= f.label :image %>
      <%= image_tag main_app.url_for(@instagram_user.image.try(:attachment)), class: 'img-thumbnail' if @instagram_user.image %>
      <%= f.file_field :image %>
    <% end %>
  </div>
</div>

app/views/spree/admin/instagram_users/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:instagram_users), admin_instagram_users_url %> /
  <%= @instagram_user.name %>
<% end %>

<%= form_for @instagram_user, url: object_url, method: :put do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/instagram_users/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::InstagramUser) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_instagram_user), new_object_url, class: "btn-success", icon: 'add' %>
<% end if can?(:create, Spree::InstagramUser) %>

<% if @instagram_users.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Spree.t(:username) %></th>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:profile_picture) %></th>
        <th data-hook="admin_instagram_users_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @instagram_users.each do |instagram_user| %>
        <tr id="<%= spree_dom_id instagram_user %>">
          <td><%= link_to instagram_user.name, edit_admin_instagram_user_path(instagram_user) %></td>
          <td><%= instagram_user.username %></td>
          <td><%= image_tag main_app.url_for(instagram_user.image.url(:thumbnail)) if instagram_user.image %></td>
          <td class="actions actions-2" data-hook="admin_instagram_users_index_row_actions">
            <%= link_to_edit instagram_user, no_text: true if can?(:edit, instagram_user) %>
            <%= link_to_delete instagram_user, no_text: true if can?(:delete, instagram_user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::InstagramUser)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::InstagramUser) %>!
  </div>
<% end %>

app/views/spree/admin/instagram_users/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:instagram_users), admin_instagram_users_url %> /
  <%= Spree.t(:new) %>
<% end %>

<%= form_for :instagram_user, url: collection_url do |f| %>
  <%= f.hidden_field :post_id, value: params[:post_id] %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>