config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :home_page_sections do
      collection do
        post :update_positions
      end
    end
    resources :home_page_fields
    resources :home_page_section_types
    resources :home_page_field_types
    resource :instagram_settings, only: %i[destroy update]
    resources :instagram_users
    resources :instagram_posts, only: [:index] do
      collection do
        get :download
        get :hashtag
        post :update_all
        get :destroy_all
      end
    end
    namespace :instagram_callbacks do
      get :connect
      get :callback
    end
  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :instagram_posts, only: %i[index]
        resources :home_page_sections, only: %i[index]
      end
    end
  end
end

app/models/spree/instagram_post.rb
module Spree
  class InstagramPost < Spree::Base
    belongs_to :product
    belongs_to :instagram_user
    scope :user, -> { where(hashtag_id: nil) }
    scope :hashtag, -> { where.not(hashtag_id: nil) }
    has_one_attached :media
    has_one_attached :profile_picture_media
  end
end

app/controllers/spree/admin/instagram_posts_controller.rb
module Spree
  module Admin
    class InstagramPostsController < ResourceController
      include Spree::Backend::Callbacks

      before_action :instagram_settings, only: %i[index hashtag download]
      before_action :products, only: %i[index hashtag]
      before_action :instagram_users, only: %i[index hashtag]
      before_action :hashtag_param, only: %i[update_all download destroy_all]

      rescue_from Koala::Facebook::AuthenticationError, with: :facebook_error
      rescue_from Koala::Facebook::ClientError, with: :facebook_error

      def index
        @instagram_posts = Spree::InstagramPost.user.order(created_at: :desc)
      end

      def hashtag
        @instagram_posts = Spree::InstagramPost.hashtag.order(created_at: :desc)
      end

      def download
        if Instagram::LoadPosts.new(@instagram_settings, @hashtag).call
          flash[:success] = Spree.t(:instagram_posts_downloaded)
        else
          flash[:error] = Spree.t(:instagram_posts_downloaded_error)
        end
        redirect_to action: @hashtag ? :hashtag : :index
      end

      def update_all
        posts = params['instagram_post']
        Spree::InstagramPost.update(posts.keys, posts.values)
        redirect_to action: @hashtag ? :hashtag : :index
      end

      def destroy_all
        @hashtag ? Spree::InstagramPost.hashtag.destroy_all : Spree::InstagramPost.user.destroy_all
        redirect_to action: @hashtag ? :hashtag : :index
      end

      private

      def instagram_settings
        @instagram_settings ||= Spree::InstagramSetting.first_or_create
      end

      def products
        @products ||= Spree::Product.all
      end

      def instagram_users
        @instagram_users ||= Spree::InstagramUser.all
      end

      def hashtag_param
        @hashtag = params[:hashtag] == 'true'
      end

      def facebook_error(exception)
        flash[:error] = exception
        redirect_to action: @hashtag ? :hashtag : :index
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/instagram_posts_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        class InstagramPostsController < Spree::Api::V2::BaseController
          def index
            resource = params[:user] ? user_posts : hashtag_posts
            render_serialized_payload { serialize_resource(resource) }
          end

          private

          def user_posts
            Spree::InstagramPost.user.where(show: true)
          end

          def hashtag_posts
            Spree::InstagramPost.hashtag.where(show: true)
          end

          def resource_serializer
            Spree::V2::Storefront::InstagramPostSerializer
          end

          def serialize_resource(resource)
            resource_serializer.new(
              resource,
              include: ['product.default_variant', :instagram_users],
              params: { base_url: request.base_url }
            ).serializable_hash
          end
        end
      end
    end
  end
end

app/helpers/spree/admin/instagram_posts_helper.rb
module Spree
  module Admin
    module InstagramPostsHelper
      def instagram_data(post)
        JSON.parse(post.data)
      end

      def instagram_link(post, content)
        link_to content, instagram_data(post)["permalink"]
      end

      def instagram_preview(post)
        return image_tag(main_app.url_for(post.media.representation(resize: "100x100"))) if post.media.attached? && post.media.representable?

        Spree.t(:no_preview)
      end
    end
  end
end

app/views/spree/admin/instagram_posts/_hashtag_form.html.erb
<% button_text = instagram_settings.hashtag_id.empty? ? Spree.t(:use_hashtag) : Spree.t(:update_hashtag)%>
<div class="row">
  <div class="col-sm-12">
    <%= form_for instagram_settings, url: {controller: :instagram_settings, action: :update} do |f| %>
      <%= f.label :hashtag %>
      <div class="input-group">
        <%= f.text_field :hashtag, class: 'form-control'  %>
        <span class="input-group-btn">
          <%= f.submit button_text, class: 'btn btn-primary' %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/admin/instagram_posts/_navigation.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <li role="presentation" class="nav-item"><a class="nav-link <%= active == :user && 'active' %>" href="<%= admin_instagram_posts_path %> ">User</a></li>
      <li role="presentation" class="nav-item"><a class="nav-link <%= active == :hashtag && 'active' %>" href="<%= hashtag_admin_instagram_posts_path %> ">Hashtag</a></li>
    </ul>
  </div>
</div>

app/views/spree/admin/instagram_posts/_no_connected.html.erb
<div class="alert alert-warning">
  <%= Spree.t(:please_connect_to_instagram) %>
</div>

app/views/spree/admin/instagram_posts/_page_actions.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:instagram_posts) %>
<% end %>

<% content_for :page_actions do %>
  <% if @instagram_settings.access_token.present? %>
    <%= button_link_to Spree.t(:disconnect), admin_instagram_settings_path, method: :delete, class: "btn-danger", icon: 'remove' %>
  <% else %>
    <%= button_link_to Spree.t(:connect), admin_instagram_callbacks_connect_path, class: "btn-success", icon: 'add' %>
  <% end %>
<% end %>

app/views/spree/admin/instagram_posts/_table.html.erb
<% if @instagram_posts.any?%>
  <%= form_for :spree_instagram_post, :url => update_all_admin_instagram_posts_path(hashtag: hashtag), :html => { :method => :post } do %>
    <div class="row">
      <div class="col-sm-12 text-right">
        <%= button_link_to Spree.t(:download_instagram_posts), download_admin_instagram_posts_path(hashtag: hashtag), class: "btn-primary", icon: 'download' %>
        <%= button Spree.t(:update_posts), 'save' %>
        <%= button_link_to Spree.t(:remove_all), destroy_all_admin_instagram_posts_path(hashtag: hashtag), class: "btn-danger", icon: 'remove' %>
      </div>
    </div>
    <table class="table instagram-posts">
      <thead>
        <tr>
          <th class="instagram-posts__head--centered"><%= Spree.t(:id) %></th>
          <th class="instagram-posts__head--centered"><%= Spree.t(:preview) %></th>
          <th><%= Spree.t(:caption) %></th>
          <th class="instagram-posts__head--centered"><%= Spree.t(:likes) %></th>
          <th class="instagram-posts__head--centered"><%= Spree.t(:product) %></th>
          <% if hashtag %>
            <th class="instagram-posts__head--centered"><%= Spree.t(:user) %></th>
          <% end %>
          <th class="instagram-posts__head--centered"><%= Spree.t(:visible) %></th>
          <th class="instagram-posts__head--centered"><%= Spree.t(:downloaded_at) %></th>
        </tr>
      </thead>
      <tbody>
      <% instagram_posts.each do |post| %>
        <%= fields_for "instagram_post[]", post do |post_fields| %>
      <tr>
        <td><%= post.id %></td>
        <td><div class="preview-container"><%= instagram_preview(post) %></div></td>
        <td class="instagram-posts__column--break-word"><%= instagram_link(post, instagram_data(post)['caption']) %></td>
        <td class="instagram-posts__column--centered"><%= instagram_data(post)['like_count'] %></td>
        <td>
          <%= post_fields.select(:product_id, @products.map { |product| [product.name, product.id] }, { include_blank: true }, { class: 'select2' }) %>
        </td>
        <% if hashtag %>
          <td>
            <div class="users">
              <%= post_fields.select(:instagram_user_id, @instagram_users.map { |user| [user.name, user.id] }, { include_blank: true }, { class: 'select2' }) %>
              <%= button_link_to '', new_admin_instagram_user_path(post_id: post.id), class: "btn-sm", icon: 'add', title: Spree.t(:create_new_user) %>
            </div>
          </td>
        <% end %>
        <td class="instagram-posts__column--centered"><%= post_fields.check_box :show %></td>
        <td><%= pretty_time post.created_at %></td>
      </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-sm-12 text-center">
      <%= button_link_to Spree.t(:download_instagram_posts), download_admin_instagram_posts_path(hashtag: hashtag), class: "btn-primary", icon: 'download' %>
    </div>
  </div>
<% end %>

app/views/spree/admin/instagram_posts/hashtag.html.erb
<%= render 'page_actions' %>

<% if @instagram_settings.access_token.present? %>
  <%= render 'navigation', active: :hashtag %>
  <%= render 'hashtag_form', instagram_settings: @instagram_settings %>
  <% unless @instagram_settings.hashtag_id.empty? %>
    <%= render 'table', instagram_posts: @instagram_posts, hashtag: true %>
  <% end %>
<% else %>
  <%= render 'no_connected' %>
<% end %>

app/views/spree/admin/instagram_posts/index.html.erb
<%= render 'page_actions' %>

<% if @instagram_settings.access_token.present? %>
  <%= render 'navigation', active: :user %>
  <%= render 'table', instagram_posts: @instagram_posts, hashtag: false %>
<% else %>
  <%= render 'no_connected' %>
<% end %>