config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :home_page_sections do
      collection do
        post :update_positions
      end
    end
    resources :home_page_fields
    resources :home_page_section_types
    resources :home_page_field_types
    resource :instagram_settings, only: %i[destroy update]
    resources :instagram_users
    resources :instagram_posts, only: [:index] do
      collection do
        get :download
        get :hashtag
        post :update_all
        get :destroy_all
      end
    end
    namespace :instagram_callbacks do
      get :connect
      get :callback
    end
  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :instagram_posts, only: %i[index]
        resources :home_page_sections, only: %i[index]
      end
    end
  end
end

app/models/spree/home_page_section.rb
module Spree
  class HomePageSection < Spree::Base
    acts_as_list

    has_many :home_page_fields
    belongs_to :home_page_section_type

    validates :name, presence: true, uniqueness: true

    before_validation :assign_name

    private

    def assign_name
      self.name = title.parameterize.underscore if name.blank?
    end
  end
end

app/models/spree/home_page_section_type.rb
module Spree
  class HomePageSectionType < Spree::Base
    has_many :home_page_types
    has_many :home_page_field_types, through: :home_page_types
    has_many :home_page_sections

    validates :name, presence: true, uniqueness: true
  end
end

app/controllers/spree/admin/home_page_sections_controller.rb
module Spree
  module Admin
    class HomePageSectionsController < ResourceController
      before_action :section_types, only: %i[new edit]

      def index
        @home_page_sections = Spree::HomePageSection.order(position: :asc)
      end

      private

      def section_types
        @section_types ||= Spree::HomePageSectionType.all
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/home_page_sections_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        class HomePageSectionsController < Spree::Api::V2::BaseController
          def index
            render_serialized_payload { serialize_resource(resource) }
          end

          private

          def resource
            Spree::HomePageSection.includes(:home_page_fields)
          end

          def resource_serializer
            Spree::V2::Storefront::HomePageSectionSerializer
          end

          def serialize_resource(resource)
            resource_serializer.new(
              resource,
              include: [:home_page_fields]
            ).serializable_hash
          end
        end
      end
    end
  end
end

app/views/spree/admin/home_page_sections/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @home_page_section } %>

<% if @section_types.empty? %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageSectionType)) %>,
    <%= link_to Spree.t(:add_one), new_admin_home_page_section_type_path if can?(:create, Spree::HomePageSectionType) %>!
  </div>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <%= f.field_container :home_page_section_type_id, class: ['form-group'] do %>
      <%= f.label :home_page_section_type_id, Spree.t(:section_type) %>
      <%= f.collection_select(:home_page_section_type_id, @section_types, :id, :name, {}, { class: 'select2' }) %>
      <%= f.error_message_on :home_page_section_type_id %>
    <% end %>
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :title, class: ['form-group'] do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.error_message_on :title %>
    <% end %>

    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <%= f.field_container :visible, class: ['form-group'] do %>
      <%= f.label :visible %>
      <%= f.check_box :visible, class: 'form-control' %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= f.field_container :mobile_visible, class: ['form-group'] do %>
      <%= f.label :mobile_visible %>
      <%= f.check_box :mobile_visible, class: 'form-control' %>
    <% end %></div>
</div>

app/views/spree/admin/home_page_sections/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:home_page_section), admin_home_page_sections_url %> /
  <%= @home_page_section.name %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_section_type), new_admin_home_page_section_type_path, { class: "btn-default", icon: 'add' } %>
<% end if can? :create, Spree::HomePageSectionType %>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="mb-0 h5">
          <%= Spree.t(:edit_section) %> - <%= @home_page_section.name %>
        </h1>
      </div>
      <div class="card-body panel-body">
        <%= form_for @home_page_section, url: object_url, method: :put do |f| %>
            <%= render partial: 'form', locals: { f: f } %>
            <%= render partial: 'spree/admin/shared/edit_resource_links' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="mb-0 h5">
          <%= Spree.t(:section_fields) %>
        </h1>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @home_page_section.home_page_fields.each do |field| %>
            <li><%= link_to field.name, edit_admin_home_page_field_path(field) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/home_page_sections/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::HomePageSection) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_field), new_admin_home_page_field_path, { class: "btn-default", icon: 'add' } if can?(:create, Spree::HomePageField) %>
  <%= button_link_to Spree.t(:new_section), new_object_url, class: "btn-success", icon: 'add' %>
<% end if can?(:create, Spree::HomePageSection) %>

<% if @home_page_sections.any? %>
  <table class="table sortable" data-sortable-link="<%= update_positions_admin_home_page_sections_url %>">
    <thead>
      <tr>
        <th></th>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:type) %></th>
        <th><%= Spree.t(:title) %></th>
        <th><%= Spree.t(:description) %></th>
        <th><%= Spree.t(:section_visible) %></th>
        <th>
          <%= Spree.t(:fields) %>
        </th>
        <th data-hook="admin_home_page_sections_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @home_page_sections.each do |section| %>
        <tr id="<%= spree_dom_id section %>">
          <td class="move-handle">
            <span class="icon icon-sort handle"></span>
          </td>
          <td><%= link_to section.name, edit_admin_home_page_section_path(section) %></td>
          <td><%= section.home_page_section_type&.name %></td>
          <td><%= section.title %></td>
          <td><%= section.description %></td>
          <td>
            <span class="icon icon-<%= section.visible ? 'ok' : 'remove' %>"></span> ( <span title="mobile" class="icon icon-<%= section.mobile_visible ? 'ok' : 'remove' %>"></span> )
          </td>
          <td>
            <% section.home_page_fields.each do |field| %>
              <%= link_to field.name, edit_admin_home_page_field_path(field) %>
            <% end %>
          </td>
          <td class="actions actions-2" data-hook="admin_home_page_sections_index_row_actions">
            <%= link_to_edit section, no_text: true if can?(:edit, section) %>
            <%= link_to_delete section, no_text: true if can?(:delete, section) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageSection)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::HomePageSection) %>!
  </div>
<% end %>

app/views/spree/admin/home_page_sections/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:home_page_section), admin_home_page_sections_url %> /
  <%= Spree.t(:new) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_section_type), new_admin_home_page_section_type_path, { class: "btn-default", icon: 'add' } %>
<% end if can? :create, Spree::HomePageSectionType %>

<%= form_for :home_page_section, url: collection_url do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>