config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :home_page_sections do
      collection do
        post :update_positions
      end
    end
    resources :home_page_fields
    resources :home_page_section_types
    resources :home_page_field_types
    resource :instagram_settings, only: %i[destroy update]
    resources :instagram_users
    resources :instagram_posts, only: [:index] do
      collection do
        get :download
        get :hashtag
        post :update_all
        get :destroy_all
      end
    end
    namespace :instagram_callbacks do
      get :connect
      get :callback
    end
  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :instagram_posts, only: %i[index]
        resources :home_page_sections, only: %i[index]
      end
    end
  end
end

app/models/spree/home_page_field.rb
module Spree
  class HomePageField < Spree::Base
    belongs_to :home_page_section
    belongs_to :home_page_field_type
    has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::HomePageFieldImage'

    validates :name, presence: true, uniqueness: true

    before_validation :assign_name

    private

    def assign_name
      self.name = title.parameterize.underscore if name.blank?
    end
  end
end

app/models/spree/home_page_field_type.rb
module Spree
  class HomePageFieldType < Spree::Base
    FIELDS = %i[
      text
      image
    ].freeze

    has_many :home_page_fields
    has_many :home_page_types
    has_many :home_page_section_types, through: :home_page_types

    validates :name, presence: true, uniqueness: true
    validates :field_type, presence: true
  end
end

app/models/spree/home_page_section_type.rb
module Spree
  class HomePageSectionType < Spree::Base
    has_many :home_page_types
    has_many :home_page_field_types, through: :home_page_types
    has_many :home_page_sections

    validates :name, presence: true, uniqueness: true
  end
end

app/controllers/spree/admin/home_page_fields_controller.rb
module Spree
  module Admin
    class HomePageFieldsController < ResourceController
      before_action :section_types
      before_action :field_types
      before_action :sections

      def create
        @home_page_field = Spree::HomePageField.new(home_page_field_params)
        @home_page_field.build_image(attachment: image_params) if image_params
        if @home_page_field.save
          flash[:success] = flash_message_for(@home_page_field, :successfully_created)
          redirect_to action: :index
        else
          flash[:error] = Spree.t(:could_not_create_page_field)
          render :new
        end
      end

      def update
        @home_page_field = Spree::HomePageField.find(params[:id])
        @home_page_field.create_image(attachment: image_params) if image_params
        if @home_page_field.update(home_page_field_params)
          flash[:success] = flash_message_for(@home_page_field, :successfully_updated)
        else
          flash[:error] = Spree.t(:could_not_update_page_field)
        end
        render :edit
      end

      private

      def image_params
        params[:home_page_field][:image]
      end

      def home_page_field_params
        params.require(:home_page_field).permit(:name, :title, :content, :home_page_section_id, :home_page_field_type_id)
      end

      def section_types
        @section_types ||= Spree::HomePageSectionType.all
      end

      def field_types
        @field_types ||= Spree::HomePageFieldType.all
      end

      def sections
        @sections ||= Spree::HomePageSection.all
      end
    end
  end
end

app/views/spree/admin/home_page_fields/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @home_page_field } %>

<% if @section_types.empty? %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageSection)) %>,
    <%= link_to Spree.t(:add_one), new_admin_home_page_section_path if can?(:create, Spree::HomePageSection) %>!
  </div>
<% end %>

<% if @section_types.empty? %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageSectionType)) %>,
    <%= link_to Spree.t(:add_one), new_admin_home_page_section_type_path if can?(:create, Spree::HomePageSectionType) %>!
  </div>
<% end %>

<% if @field_types.empty? %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageFieldType)) %>,
    <%= link_to Spree.t(:add_one), new_admin_home_page_field_type_path if can?(:create, Spree::HomePageFieldType) %>!
  </div>
<% end %>

<div class="home-page-field-form">
  <div class="row">
    <div class="col-sm-6">
      <%= f.field_container :home_page_section, class: ['form-group'] do %>
        <%= f.label :home_page_section, Spree.t(:section) %>
        <%= f.select :home_page_section_id, @sections.map { |s| [s.name , s.id, 'data-home-page-field-types': s.home_page_section_type&.home_page_field_type_ids] }, {}, { class: "select2" } %>
        <%= f.error_message_on :home_page_section %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <%= f.field_container :home_page_field_type, class: ['form-group'] do %>
        <%= f.label :home_page_field_type, Spree.t(:type) %>
        <%= f.select :home_page_field_type_id, @field_types.map { |ft| [ft.name , ft.id, 'data-type': ft.field_type] }, { include_blank: true }, { class: "select2" } %>
        <%= f.error_message_on :home_page_field_type %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= f.field_container :name, class: ['form-group'] do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.error_message_on :name %>
      <% end %>

      <%= f.field_container :title, class: ['form-group'] do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.error_message_on :title %>
      <% end %>

      <%= f.field_container :content, class: ['form-group'] do %>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      <% end %>

      <%= f.field_container :image, class: ['form-group'] do %>
        <%= f.label :image %>
        <%= image_tag main_app.url_for(@home_page_field.image.try(:attachment)), class: "img-thumbnail" if @home_page_field.image %>
        <%= f.file_field :image %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/home_page_fields/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:home_page_fields), admin_home_page_fields_url %> /
  <%= @home_page_field.name %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_field_type), new_admin_home_page_field_type_path, { class: "btn-default", icon: 'add' } %>
<% end if can? :create, Spree::HomePageFieldType %>

<%= form_for @home_page_field, url: object_url, method: :put do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= render partial: 'form', locals: { f: f } %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </div>
<% end %>

app/views/spree/admin/home_page_fields/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::HomePageField) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_field), new_object_url, class: "btn-success", icon: 'add' %>
<% end if can?(:create, Spree::HomePageField) %>

<% if @home_page_fields.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:title) %></th>
        <th><%= Spree.t(:content) %></th>
        <th><%= Spree.t(:type) %></th>
        <th><%= Spree.t(:section) %></th>
        <th data-hook="admin_home_page_fields_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @home_page_fields.each do |field| %>
        <tr id="<%= spree_dom_id field %>">
          <td><%= link_to field.name, edit_admin_home_page_field_path(field) %></td>
          <td><%= field.title %></td>
          <td>
            <% if field.home_page_field_type&.field_type === 'image' %>
              <%= image_tag main_app.url_for(field.image.url(:thumbnail)) if field.image %>
            <% else %>
              <%= field.content %>
            <% end %>
          </td>
          <td><%= field.home_page_field_type&.name %></td>
          <td><%= field.home_page_section ? (link_to field.home_page_section&.name, edit_admin_home_page_section_path(field.home_page_section)) : '' %></td>
          <td class="actions actions-2" data-hook="admin_home_page_fields_index_row_actions">
            <%= link_to_edit field, no_text: true if can?(:edit, field) %>
            <%= link_to_delete field, no_text: true if can?(:delete, field) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomePageField)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::HomePageField) %>!
  </div>
<% end %>

app/views/spree/admin/home_page_fields/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:home_page_fields), admin_home_page_fields_url %> /
  <%= Spree.t(:new) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_field_type), new_admin_home_page_field_type_path, { class: "btn-default", icon: 'add' } %>
<% end if can? :create, Spree::HomePageFieldType %>

<%= form_for :home_page_field, url: collection_url do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>